name: CI
on: [pull_request, push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v4.1.7
      - run: ${{ env.CC }} --version
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12.4'
          cache: 'pip'
      - name: Update pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip --version
      - name: Install VapourSynth
        uses: rlaphoenix/install-vapoursynth-action@master
        with:
          version: 68
          cache: true
      - run: python3 -m pip inspect
      - name: Verify VapourSynth install
        run: python3 -c "import vapoursynth; print(vapoursynth.core.version())"
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt -r requirements-dev.txt
      - name: vs-jet latest
        run: vsjet latest
      - name: mypy
        run: for dir in src/*/; do python3 -m mypy --ignore-missing-imports "$dir"; done
        continue-on-error: true
      - name: flake8
        run: python3 -m flake8
        continue-on-error: true
      - name: black
        run: python3 -m black --check --diff .
        continue-on-error: true
      - name: isort
        run: python3 -m isort --check --diff .
        continue-on-error: true
