name: CI
on: [pull_request, push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v4
      - run: ${{ env.CC }} --version
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          cache: 'pip'
      - name: Update pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip --version
      - name: Install VapourSynth
        uses: rlaphoenix/install-vapoursynth-action@master
        with:
          version: 70
          cache: true
      - run: python3 -m pip inspect
      - name: Verify VapourSynth install
        run: python3 -c "from vapoursynth import core; print(core)"
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt -r requirements-dev.txt
      - name: vs-jet latest
        run: vsjet latest
      - name: Running ruff
        run: ruff check encode-script
        continue-on-error: true
