name: lint

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install VapourSynth
        uses: deadnews/action-setup-vs@latest
      - name: Install dependencies
        id: dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8
      - name: Running flake8
        run: flake8 .
      # - name: Running mypy
      #   if: steps.dependencies.outcome == 'success'
      #   run: mypy -p .
